# Generated by Django 2.1.3 on 2018-11-12 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorArcanaCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('meaning', models.TextField()),
                ('imgUrl', models.URLField()),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=200)),
                ('altText', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MinorArcanaCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('meaning', models.TextField()),
                ('imgUrl', models.URLField()),
                ('suit', models.CharField(choices=[('SW', 'Swords'), ('CP', 'Cups'), ('WD', 'Wands'), ('PT', 'Pentacles'), (None, 'Select a suit')], default=None, max_length=2)),
                ('face', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('P', 'Page'), ('N', 'Knight'), ('Q', 'Queen'), ('K', 'King'), (None, 'Select a face')], default=None, max_length=1)),
                ('altText', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
