# Generated by Django 2.1.3 on 2018-12-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20181111_1911_squashed_0005_auto_20181112_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='placement',
            name='spread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Spread'),
        ),
    ]
