# Generated by Django 2.1.3 on 2018-12-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20181207_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorarcanacard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='minorarcanacard',
            name='description',
        ),
    ]
